apiVersion: batch/v1
kind: Job
metadata:
  name: search-deploy
spec:
  template:
    spec:
      containers:
      - name: mastodon
        image: ghcr.io/mastodon/mastodon:nightly@sha256:f0b505f180432ae2e333843f8059d30b8b679c9a80a0d7b092243a49224d6440
        envFrom:
        - configMapRef:
            name: mastodon-env
        - secretRef:
            name: mastodon
        command: ["./bin/tootctl", "search", "deploy"]
      restartPolicy: Never
